# Generated by Django 3.0.4 on 2020-03-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название комнаты')),
                ('description', models.TextField(verbose_name='описание комнаты')),
                ('items', models.ManyToManyField(blank=True, related_name='in_rooms', to='pages.Item', verbose_name='предметы в комнате')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('items', models.ManyToManyField(blank=True, related_name='in_inventory', to='pages.Item', verbose_name='предметы в инвентаре')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='pages.Room', verbose_name='комната, где находится персонаж')),
            ],
        ),
    ]
